//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interop {
    using Microsoft.InteropFormTools;
    using System;
    
    
    [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.AutoDual)]
    [System.Runtime.InteropServices.ComVisible(true)]
    public partial class ExampleForm : InteropFormProxyBase {
        
        public ExampleForm() {
            FormInstance = new InteropExample.Forms.ExampleForm();
            RegisterFormInstance();
        }
        
        public virtual string Content {
            get {
            InteropExample.Forms.ExampleForm castFormInstance = (InteropExample.Forms.ExampleForm)FormInstance;
                return castFormInstance.Content;
            }
            set {
            InteropExample.Forms.ExampleForm castFormInstance = (InteropExample.Forms.ExampleForm)FormInstance;
                castFormInstance.Content = value;
            }
        }
    }
}
